### ISSUE TITLE
Please add a Free license

### ISSUE THREAD

**Issue by heylix** [HrBingR/Lemmy_CSS#11]
Hi, it would be cool if you could ask all of the contributors to provide their work under a Free license so Beehaw could actually use this in the theme selector if possible.

I'm currently looking into a way of bringing all of those in the theme selector by simply pulling this github repo and merging it with a beehaw one.

**Comment by heylix** [comment]
We're currently looking into how the attribution works. A `CC0` license would certainly be easier if you would be open to that. We **want** to attribute, however there's not a good way in the Lemmy UI we **could**.

Could you outline on how you'd want the attribution to be done? Would it be enough to just add the link to the repo and the authors at the top of the CSS files themselves?

**Comment by HrBingR** [comment]
So I would be 100% happy with attribution exactly the way you described. Not going to ask that anything be added to the UI or anything like that, literally just a link to the repo and authors in the CSS would be perfect.

**Comment by HrBingR** [comment]
This repo has been marked with CC0, providing free access to use, modify, and freely redistribute any code or content uploaded to this repo per https://github.com/HrBingR/Lemmy_CSS/blob/main/LICENSE.md, without requiring any attribution.
