### ISSUE TITLE
[Feature Request] Use the UserCSS guide

### ISSUE THREAD

**Issue by Generator** [HrBingR/Lemmy_CSS#4]
Using the UserCSS makes it easier for users and developer to manage user.css. 
Just renaming file.css to file.user.css automatically will prompt to install.  
https://github.com/openstyles/stylus/wiki/Writing-UserCSS

Also you can merge all into one CSS, here's an example:   
 https://github.com/catppuccin/brave-search/raw/main/catppuccin.user.css

**Comment by HrBingR** [comment]
Done! See themes/lemmy_css.user.css

[Click here for the raw file/easy installation](https://raw.githubusercontent.com/HrBingR/Lemmy_CSS/main/themes/lemmy_css.user.css)

Let me know if you pick up any issues.
