### ISSUE TITLE
[Comment] Great job!

### ISSUE THREAD

**Issue by monerobull** [HrBingR/Lemmy_CSS#5]
I really like the orange css. Can't wait for a darkmode version of it!

If you could perhaps make a monero-darkmode-theme (based on FF6600 + 4C4C4C but perhaps adjusted for readability) that would be awesome, pretty please 🥺🙏

**Comment by monerobull** [comment]
I've noticed that the orange theme is sub-optimal for mobile (at least on my instance). There is an empty gap on the right side of the screen. Someone posted a very long link that goes outside of the orange post box so perhaps that shifted all the other posts to the side?

**Comment by HrBingR** [comment]
That's entirely possible; currently the themes don't account for screen sizes, will fix that, thank you.

**Comment by HrBingR** [comment]
So the size issue should be fixed, but I'll keep this issue open until I have a dark theme ready to go.

**Comment by HrBingR** [comment]
I've added a theme based on Monero, as well as a normal dark orange theme. Actually, I've added a bunch of dark themes, feel free to check them out!

I've also fixed the spacing issue, so mobile should no longer be impacted, let me know if you still experience issues.

**Comment by monerobull** [comment]
That is so unbelievably cool, ill try it out and probably put it as default for monero.town ❤
