### ISSUE TITLE
Colors change but elements are not resized

### ISSUE THREAD

**Issue by kabe-inc** [HrBingR/Lemmy_CSS#9]
When I first applied the CSS earlier today it looked correct, but now it has gone back to the old Lemmy UI (text fields, post boxes, etc.) but with different colors.

For reference, this is what Lemmy looks like with the darkly CSS theme applied
 
![Screenshot from 2023-06-13 23-47-11](https://github.com/HrBingR/Lemmy_CSS/assets/72587902/a9e91a9d-a38d-4980-a82c-a621cdf1e5c3)

Firefox 114.0.1 with Stylus Extension.

**Comment by HrBingR** [comment]
Does the problem persist if you disable and re-enable Stylus while on your Lemmy instance?

Occasionally Amino (the extension I use) doesn't fully render all of the changes correctly, often only changing colors, but disabling and re-enabling the extension tends to fix it.

**Comment by kabe-inc** [comment]
Hi, I did this and it didn't do anything, however I went ahead and checked the litely theme and found that it worked. 
So it seems to be a darkly theme issue - even removing everything and reinstalling Stylus and the CSS theme from scratch results in the appearance in the screenshot above.

**Comment by HrBingR** [comment]
Okay I see that the darkly theme doesn't do any resizing, I'll make some changes and let you know once fixed!

**Comment by HrBingR** [comment]
Okay this has been fixed, Ancom should now correctly resize as expected.
